language: php

env:
  global:
    - PLUGIN_NAME=AdvancedShell
    - PLUGIN_PATH=Plugin/AdvancedShell
    - REQUIRE=""
    - DB=mysql
    - CAKE_VERSION=2.4

matrix:
  include:
    - php: 5.4
      env:
        - COVERALLS=1
    - php: 5.4
      env:
        - PHPCS=1
    - php: 5.4
      env:
        - FOC_VALIDATE=1
        
before_script:
  - git clone https://github.com/FriendsOfCake/travis.git --depth 1 ../travis
  - ../travis/before_script.sh
  - if [ "$PHPCS" != 1 ]; then
        echo "
            CakePlugin::load('AdvancedShell', array('bootstrap' => true, 'routes' => false));
        " >> ../cakephp/app/Config/bootstrap.php;
    fi
  - if [ "$PHPCS" == 1 ]; then
      rm -rf ~/.phpenv/versions/$(phpenv version-name)/pear/PHP/CodeSniffer/Standards/CakePHP;
      git clone https://github.com/imsamurai/cakephp-codesniffer.git --depth 1 ~/.phpenv/versions/$(phpenv version-name)/pear/PHP/CodeSniffer/Standards/CakePHP;
    fi
  - echo "<?php
    class DATABASE_CONFIG {
    public \$test = array(
        'datasource' => 'Database/Mysql',
        'host' => '127.0.0.1',
        'login' => 'travis',
        'database' => 'cakephp_test',
        'prefix' => '',
        'encoding' => 'utf8'
    );

    }" > ../cakephp/app/Config/database.php
  
script:
  - ../travis/script.sh

after_success:
  - ../travis/after_success.sh

notifications:
  email: im.samuray@gmail.com