language: php

php:
  - 5.4
  - 5.5
  - hhvm

env:
  global:
    - PLUGIN_NAME=AdvancedShell
    - PLUGIN_PATH=Plugin/AdvancedShell
    - REQUIRE="imsamurai/cakephp-environment:dev-master phpdocumentor/phpdocumentor:2.*"
    - DB=mysql
    - CAKE_VERSION=2.5
    - secure: v85/4N9rEbsWV1UFgE6B1pi2qmGvrW9tazFlSFL/gj9dcVakIWuYQFWmja7OChy0bcMJL2hjdVpjfcPVYqWwqcPsbqYD941Yu/8ktrOgapsk5xNAjPZzzaLHtHvK1UNPJ/DJLvkERlsMaxVP2MGwVPXV3rl8O9qWc63T3oKw0OI=
  matrix:
    - CAKE_VERSION=2.4
    - CAKE_VERSION=2.5

matrix:
  include:
    - php: 5.5
      env:
        - COVERALLS=1
    - php: 5.5
      env:
        - PHPCS=1
    - php: 5.5
      env:
        - FOC_VALIDATE=1
    - php: 5.5
      env:
        - PHPDOC=1

before_script:
  - git clone git://github.com/imsamurai/travis-plugin-build.git --depth 1 travis
  - chmod +x ./travis/*
  - ./travis/before_script.sh

script:
  - ./travis/script.sh

after_success:
  - ./travis/after_success.sh

notifications:
  email: im.samuray@gmail.com